ignore = [
    "node_modules",
    "build",
    "dist",
    "coverage",
    "venv",
    ".git",
    "public",
    "package-lock.json",
    "turbo_docs.toml",
    ".gitignore",
    ".requirements.txt",
    "README.md",
    ".env",
    "__pycache__",
    "assets",
]