
ignore = [
    "node_modules",
    "build",
    "dist",
    "coverage",
    "venv",
    ".git",
    "public",
    "images",
    "package-lock.json",
    "package.json",
    "turbo_docs.toml",
    ".gitignore",
    ".requirements.txt",
    "README.md",
    ".env",
    "__pycache__",
    "assets",
    "repodata",
    "reportWebVitals.js",
    "requirements.txt",
    "Skills.js",
    "Theme.js",
    "Navbar.js",
#     "config.py",
#     "services.py",
    # "app.py",
    # "Portfolio.js",
    # "Project.js",
    # "Chat.js",
]