ignore = [
    "node_modules",
    "build",
    "dist",
    "coverage",
    "venv",
    ".git",
    "public",
    "package-lock.json",
    "package.json",
    "turbo_docs.toml",
    ".gitignore",
    ".requirements.txt",
    "README.md",
    ".env",
    "__pycache__",
    "assets",
    "reportWebVitals.js",
    "index.js",
    "Skills.js",
    "Navbars.js",
    "Portfolio.js",
]